services:
  wasm-web:
    image: ghcr.io/krmckone/rusty-wasm-gfx:latest
    container_name: wasm-nginx
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    restart: unless-stopped
    depends_on:
      - wasm-web
    command: tunnel --no-autoupdate run 
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN} # from the .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 wasm-nginx
    restart: unless-stopped
