name: Build and Publish Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Rust Cach
        uses: swatinem/rust-cache@v2

      - name: Install Trunk
        run: curl -L "https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz" | tar -xzf - -C /usr/local/bin/

      - name: Build Wasm (Release)
        run: trunk build --release

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64 # Cross-compiles the Nginx wrapper for Pi
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
